# Site settings
<<<<<<< HEAD
# {{ site.myvariable }}
title: Jessica David, Cat Mom
description: >-
  Personal site for Jessica David
url: "https://jeska.me"
github_username: jeska

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - .gitignore

email:
baseurl: "" # the subpath of your site, e.g. /blog/
